# Generated by Django 2.2 on 2020-09-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduserprofile',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
