# Generated by Django 2.2 on 2020-09-15 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200915_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduserprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='adduserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
