# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-08 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_video_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_deleted',
            field=models.BooleanField(default=datetime.datetime(2020, 5, 8, 14, 18, 25, 936959, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
