# Generated by Django 2.2 on 2020-07-20 07:03

from django.db import migrations, models
import django.utils.timezone
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200715_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profile_image/'),
            preserve_default=False,
        ),
    ]
