# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-10 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200508_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='is_deleted',
        ),
    ]
