# Generated by Django 2.2 on 2020-09-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200915_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduserprofile',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
