# Generated by Django 2.2 on 2020-08-14 17:46

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200814_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profile_image/'),
        ),
    ]
