# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-04 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_last_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_edited',
        ),
    ]
