# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-05 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200505_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.upload_location),
        ),
    ]
